### ISSUE TITLE
Handle enemy-projectile collisions

### ISSUE THREAD

**Issue by jimbo00000** [DanielMGessel/BostonLinux-Graphics#3]
Check for and handle collisions between projectiles and squares every frame. When a collision between square(enemy) and projectile occurs, remove both from the scene. A simple proximity calculation should suffice, modeling each shape as a sphere by calculating only the distance between centers.

(depends on #2)

**Comment by BrianJLevine** [comment]
Jim, I took your suggestion and just did it based on the distance between two points, not taking into account the width and height of the objects.  At some point my OCD will take over and I'll got back and change it.

**Comment by jimbo00000** [comment]
Nice, this looks awesome! Great work.
